web/gep_project/gep_app/urls.py
from django.urls import path
from django.conf.urls import include
from . import views

urlpatterns = [
	path('accounts/',include('django.contrib.auth.urls')),
	path('',views.home,name='home'),
	path('change_password',views.change_password,name='change_password'),
	path('student/home',views.student_home,name='student_home'),
	path('student/home/electives',views.preference_submission,name='preference_submission'),
	path('error',views.test_failure,name='test_failure'),
	path('faculty/home',views.faculty_home,name='faculty_home'),
	path('department/home',views.department_home,name='department_home'),
]

web/gep_project/gep_project/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('',include('gep_app.urls')),
    path('admin/', admin.site.urls),
]

web/gep_project/gep_app/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from decimal import Decimal
from django.core.validators import MaxValueValidator, MinValueValidator

class User(AbstractUser):
	STUDENT = 'S'
	FACULTY = 'F'
	DEPARTMENT = 'D'
	ROLE_CHOICES = ((STUDENT,'Student'),(FACULTY,'Faculty'),(DEPARTMENT,'Department'))

	username = models.CharField(max_length=10,primary_key=True)
	password = models.CharField(max_length=100,blank=True,null=True)
	role = models.CharField(max_length=1,choices=ROLE_CHOICES)
	email = models.EmailField(max_length=100)
	USERNAME_FIELD = 'username'

	def is_student(self):
		return (self.role == get_user_model().STUDENT)

	def is_faculty(self):
		return (self.role == get_user_model().FACULTY)

	def is_department(self):
		return (self.role == get_user_model().DEPARTMENT)

	def __str__(self):
		return '%s (%s)' % (getattr(self, self.USERNAME_FIELD), self.get_role_display())

class Department(models.Model):
	user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
	name = models.CharField(max_length=100)

	def __str__(self):
		return '%s (%s)' % (self.name, self.user.username)

class Faculty(models.Model):
	user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	dept = models.ForeignKey(Department, on_delete=models.CASCADE)

	def __str__(self):
		return '%s (%s)' % (self.name, self.user.username)

class Course(models.Model):
	MODE_OF_ALLOTMENT_CHOICES = (('FCFS','First Come First Served'),('CGPA','Current CGPA'),)
	course_id = models.CharField(max_length=10,primary_key=True)
	name = models.CharField(max_length=200,unique=True)
	dept = models.ForeignKey(Department, on_delete=models.CASCADE)
	credits = models.IntegerField(validators=[MinValueValidator(0)])
	pre_requisites = models.TextField(max_length=500,blank=True,null=True)
	cot_requisite = models.BooleanField(default=False)
	cgpa_cutoff = models.IntegerField(default=0,validators=[MinValueValidator(0), MaxValueValidator(10)])
	mode_of_allotment = models.CharField(max_length=4,choices=MODE_OF_ALLOTMENT_CHOICES)

	def __str__(self):
		return '%s (%s)' % (self.name, self.course_id)
	
class Student(models.Model):
	SLOT_CHOICES = (('A','Slot A'),('B','Slot B'),('C','Slot C'),('D','Slot D'),('E','Slot E'),('F','Slot F'),('G','Slot G'),('H','Slot H'),('P','Slot P'),('Q','Slot Q'),('R','Slot R'),('S','Slot S'),('T','Slot T'),)
	SEMESTER_CHOICES = ((1,'Semester I'),(2,'Semester II'),(3,'Semester III'),(4,'Semester IV'),(5,'Semester V'),(6,'Semester VI'),(7,'Semester VII'),(8,'Semester VIII'),(9,'Semester IX'),(10,'Semester X'),)

	user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	date_of_birth = models.DateField()
	FA = models.ForeignKey(Faculty, on_delete=models.PROTECT)
	dept = models.ForeignKey(Department, on_delete=models.CASCADE)
	current_CGPA = models.DecimalField(blank=True,null=True,decimal_places=2,max_digits=4,validators=[MinValueValidator(0),MaxValueValidator(10)])
	next_semester = models.IntegerField(blank=True,null=True,choices=SEMESTER_CHOICES)
	core_slots = ArrayField(models.CharField(max_length=1,choices=SLOT_CHOICES),blank=True,null=True)
	past_courses = models.ManyToManyField(Course,blank=True,null=True)
	required_elective_count = models.IntegerField(blank=True,null=True,validators=[MinValueValidator(0)])
	submission_datetime = models.DateTimeField(blank=True,null=True)

	def __str__(self):
		return '%s (%s)' % (self.name, self.user.username)

	def has_submitted(self):
		return self.submission_datetime is not None

class Elective(models.Model):
	SLOT_CHOICES = (('A','Slot A'),('B','Slot B'),('C','Slot C'),('D','Slot D'),('E','Slot E'),('F','Slot F'),('G','Slot G'),('H','Slot H'),('P','Slot P'),('Q','Slot Q'),('R','Slot R'),('S','Slot S'),('T','Slot T'),)

	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	slot = models.CharField(max_length=1,choices=SLOT_CHOICES)
	faculty = models.ForeignKey(Faculty,blank=True,null=True, on_delete=models.SET_NULL)

	class Meta:
		unique_together = ('course', 'slot')

	def __str__(self):
		return '%s-%s' % (self.course.name, self.slot)

class Elective_Seats(models.Model):
	elective =  models.ForeignKey(Elective, on_delete=models.CASCADE) 
	dept = models.ForeignKey(Department, on_delete=models.CASCADE)
	max_seats = models.IntegerField()

	class Meta:
		unique_together = ('elective', 'dept')

	def __str__(self):
		return '%s-%s-%s (%d)' % (self.dept.name, self.elective.course.name, self.elective.slot, self.max_seats)

class COT_Allotment(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	elective = models.ForeignKey(Elective, on_delete=models.CASCADE)

	class Meta:
		unique_together = ('student', 'elective')
		
	def __str__(self):
		return '%s-%s-%s' % (self.student.name, self.elective.course.name, self.elective.slot)

class Elective_Allotment(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	elective = models.ForeignKey(Elective, on_delete=models.CASCADE)

	class Meta:
		unique_together = ('student', 'elective')

	def __str__(self):
		return '%s-%s-%s' % (self.student.name, self.elective.course.name, self.elective.slot)

class Elective_Preference(models.Model):
	student = models.ForeignKey(Student, on_delete=models.CASCADE)
	elective = models.ForeignKey(Elective, on_delete=models.CASCADE)
	priority_rank = models.IntegerField(validators=[MinValueValidator(0)])

	class Meta:
		unique_together = ('student', 'elective')

	def __str__(self):
		return '%s-%s-%s (%d)' % (self.student.name, self.elective.course.name, self.elective.slot, self.priority_rank)

web/gep_project/gep_app/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import Http404
from django.contrib.auth import authenticate, login as auth_login , logout as auth_logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.db.models import Q
from .models import Student, Elective, Faculty, Department, Elective_Preference, COT_Allotment
from .forms import StudentAcademicsForm, CourseCreationForm, AddElectiveForm

def login(request):
	if request.method == 'POST':
		user = authenticate(request,username=request.POST['username'],password=request.POST['password'])
		if user is not None:
			auth_login(request, user)
			redirect('home')
	else:
		return render(request, 'registration/login.html')

def student_check(user):
	"""Check if user is a student"""
	return user.is_student()

def faculty_check(user):
	"""Check if user is a student"""
	return user.is_faculty()

def department_check(user):
	"""Check if user is a department"""
	return user.is_department()

def academic_details_check(user):
	"""Check if student user has submitted academics details"""
	student = Student.objects.get(user=user)
	return student.has_submitted()

@login_required
def home(request):
	user = request.user
	if student_check(user):
		return redirect('student_home')
	elif faculty_check(user):
		return redirect('faculty_home')
	elif department_check(user):
		return redirect('department_home')
	else:
		raise Http404

@login_required
@user_passes_test(student_check)
def student_home(request):
	user = request.user
	student = Student.objects.get(user=user)
	
	if request.method == 'POST':
		form = StudentAcademicsForm(request.POST, instance=student)
		if form.is_valid():
			form.save()
	else:
		form = StudentAcademicsForm(instance=student)
		
	context = {
		'user':user.username,
		'student_name': student.name,
		'form':form,
	}
	return render(request, 'student/home.html', context)

@login_required
@user_passes_test(student_check)
def test_failure(request):
	return render(request, 'student/test_failure.html')

def preference_list_check(student,elective_id=None):
	"""Checks whether the student has submitted the elective preference list"""
	if elective_id is None:
		return Elective_Preference.objects.filter(student=student).exists()
	else:
		return Elective_Preference.objects.filter(student=student,elective_id=elective_id).exists()

def get_eligible_electives(student):
	""" Return all electives eligible for which the student is eligible ordered by slot and department"""
	#1) All electives ordered by slot and department
	electives = Elective.objects.all().order_by('slot', 'course__dept__name')
	#2) Filter global electives
	global_electives = electives.filter(~Q(course__dept=student.dept))
	#3) Filter out electives that were already taken
	not_taken_electives = global_electives.filter(~Q(course__in=student.past_courses.all()))
	#4) Filter out electives offered in slots of core courses
	slot_satisfied_electives = not_taken_electives.filter(~Q(slot__in=student.core_slots))
	#5) Filter electives with CGPA requirement satisfied
	cgpa_satisfied_electives = slot_satisfied_electives.filter(course__cgpa_cutoff__lte=student.current_CGPA)
	#6) Filter electives with COT requirement satisfied
	cot_satisfied_electives = [elective for elective in cgpa_satisfied_electives if not elective.course.cot_requisite or COT_Allotment.objects.filter(student=student,elective=elective).exists()]
	return cot_satisfied_electives

def get_preference_list(student):
	"""Returns elective preference list submitted by the student along with new electives and after removing removed electives"""
	#1) All electives submitted by the student
	elective_ids = Elective_Preference.objects.filter(student=student).order_by('priority_rank').values_list('elective',flat=True)
	electives = list(Elective.objects.filter(pk__in=elective_ids))
	#2) Add recently added electives in the end
	recently_added_electives = list(set(get_eligible_electives(student)) - set(electives))
	electives.extend(recently_added_electives)
	#3) Remove recently removed electives
	recently_removed_electives = list(set(electives) - set(get_eligible_electives(student)))
	return [elective for elective in electives if elective not in recently_removed_electives]

@login_required
@user_passes_test(student_check)
@user_passes_test(academic_details_check, login_url='test_failure_page')
def preference_submission(request):
	user = request.user
	student = Student.objects.get(user=user)
	if request.method == 'POST':
		elective_ids = Elective.objects.all().values_list('id',flat=True)
		for key, value in request.POST.items():
			try:
				elective_id = int(key)
			except ValueError:
				continue
			if elective_id not in elective_ids:
				continue
			if preference_list_check(student,elective_id):
				allotment = Elective_Preference.objects.get(student=student, elective_id=elective_id)
				allotment.priority_rank = value
				allotment.save()
			else:
				allotment = Elective_Preference.objects.create(student=student, elective_id=elective_id, priority_rank=value)
				
	electives = get_preference_list(student)
	context = {
		'electives':electives,
	}
	return render(request, 'student/preference_submission.html', context)

@login_required
@user_passes_test(faculty_check)
def faculty_home(request):
	return render(request, 'faculty/home.html', context)

@login_required
@user_passes_test(department_check)
def department_home(request):
	user = request.user
	user_dept = Department.objects.get(user=user)
	depts = Department.objects.all()	
	slots = Elective.SLOT_CHOICES
	faculties = Faculty.objects.all().order_by('name')	

	if request.method == 'POST':
		print(request.POST)
		course_form = CourseCreationForm(request.POST)
		hidden_form = AddElectiveForm(request.POST)
		if course_form.is_valid() and hidden_form.is_valid():
			course_form.save(user_dept)
	else:
		course_form = CourseCreationForm()
		hidden_form = AddElectiveForm()

	context = {
		'user_dept':user_dept,
		'depts':depts,
		'slots':slots,
		'faculties':faculties,
		'form':course_form,
		'hidden_form':hidden_form,
	}
	return render(request, 'department/home.html', context)
	
def change_password(request):
	context = {}
	form = LoginForm(request.POST)
	if form.is_valid():
		cd = form.cleaned_data
	return render(request, 'change_password.html', context)

def logout(request):
	auth_logout(request)
	return redirect('login')

web/gep_project/gep_app/templates/student/home.html
{% extends "base.html" %}
{% load static %}

{% block main_content %}
<div class="container-fluid">
	<a class="col-sm-12 text-right btn btn-link text-success" href="{% url 'logout' %}">Logout</a>
	<div class="h4 col-sm-12 text-center text-success">Stage 1: Submission of Academic Details</div>
	<form action="{% url 'student_home' %}" method="post">
		{% csrf_token %}
		<div class="form-group">
			<label class="form-label" for="id_user">Roll Number</label>
			<div class="form-control form-control-disabled">{{user}}</div>
		</div>
		<div class="form-group">
			<label class="form-label" for="id_name">Name</label>
			<div class="form-control form-control-disabled">{{student_name}}</div>
		</div>
		<div class="form-group">
			<label class="form-label" for="id_next_semester">Registering semester</label>
			{{form.next_semester}}
			{{form.next_semester.errors}}
		</div>
		<div class="form-group">
			<label class="form-label" for="id_current_CGPA">CGPA upto previous semester</label>
			{{form.current_CGPA}}
			{{form.current_CGPA.errors}}
		</div>
		<div class="form-group">
			<label class="form-label" for="id_required_elective_count">Number of global electives to be taken in coming semester (Including overloading)</label>
			{{form.required_elective_count}}
			{{form.required_elective_count.errors}}
		</div>
		<div class="form-group">
			<label class="form-label" for="id_past_courses">Electives that are taken before</label>
			{{form.past_courses}}
			{{form.past_courses.errors}}
		</div>
		<div class="form-group">
			<label class="form-label" for="id_core_slots">Slots of core courses to be taken in coming semester (Including overloading)</label>
			{{form.core_slots}}
			{{form.core_slots.errors}}
		</div>
		<input class="btn btn-success" type="submit" value="Submit"/>
	</form>
</div>
{% endblock %}

web/gep_project/gep_app/templates/student/preference_submission.html
{% extends "base.html" %}
{% load static %}

{% block js_files %} 
<script type="application/javascript" src="{% static 'gep_app/js/sortable.js' %}"></script>
{% endblock %}

{% block main_content %}
<div class="container-fluid">
	<a class="col-sm-12 text-right btn btn-link text-success" href="{% url 'logout' %}">Logout</a>
	<div class="h4 col-sm-12 text-center text-success">Stage 2: Submission of Elective Preferances</div>
	<form action="{% url 'preference_submission' %}" method="post">
		{% csrf_token %}		 
		<table class="table table-striped table-hover">
			<thead>
			<tr>
			    <th scope="col">Preference</th>
				<th scope="col">Course ID</th>
				<th scope="col">Course</th>
				<th scope="col">Department</th>
				<th scope="col">Slot</th>
				<th scope="col">Faculty</th>
			</tr>
			</thead>
			<tbody id="sortable-container">
				{% for elective in electives %}
				<tr class="sortable-element">
					<td><input name="{{elective.id}}" class="sortable-input text-center" type=number min=1 max={{electives|length}} value={{forloop.counter}}></td>
					<td>{{elective.course.course_id}}</td>
					<td>{{elective.course.name}}</td>
					<td>{{elective.course.dept.name}}</td>
					<td>{{elective.slot}}</td>
					<td>{{elective.faculty.name}}</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
		<input class="btn btn-success" type="submit" value="Submit"/>
	</form>
</div>
{% endblock %}

web/gep_project/gep_app/templates/student/test_failure.html
{% extends "base.html" %}
{% load static %}

{% block main_content %}
<div class="container-fluid">
	<a class="col-sm-12 text-right btn btn-link text-success" href="{% url 'logout' %}">Logout</a>
	<div class="h4 col-sm-12 col-md-8 offset-md-2 text-center text-danger mt-sm-5">Sorry you are not allowed to proceed to this stage as you have not completed the previous stages of allotment</div>
	<div class="h6 col-sm-12 col-md-8 offset-md-2 text-center text-danger">(Contact Students Affairs Counsel for further information)</div>
</div>
{% endblock %}